### ISSUE TITLE
An error in your Code

### ISSUE THREAD

**Issue by EsakaK** [chxy95/Deep-Mutual-Learning#6]

**Comment by chxy95** [comment]
I think you should learn to understand the most basic knowledge before you comment.

**Comment by TogelBian** [comment]
Emmm, Maybe my way of expression makes you uncomfortable and I'm indeed new to Machine learning. However I'm familiar with Python. So I am puzzled that If the Trainer is a basic Python Class, how can it use the method of nn.Mudules 'loss_fn' and the member 'model'.
I would love to get an explanation though I am a learner. And thank you for your reply.

**Comment by chxy95** [comment]
@TogelBian I don't think you are familiar enough with Python or how to train a network by Python.  'Trainer' is not a part of the network, and it is indeed a basic Python Class. If you have read and understood any repo coded by Pytorch or any other framework, you wouldn't have such a doubt.  Before trying to understand methods and algorithms, I strongly recommend you to read some basic tutorials first.

**Comment by chxy95** [comment]
@TogelBian BTW, if there is such a low-level and serious mistake in this code, so tell me why the dozens of people who starred the repo didn't find it.
